# Generated by Django 5.1.4 on 2024-12-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('doctor_name', models.CharField(max_length=100)),
                ('message', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('meet_time', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialization', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=500)),
                ('time8', models.BooleanField()),
                ('time9', models.BooleanField()),
                ('time10', models.BooleanField()),
                ('time11', models.BooleanField()),
                ('time12', models.BooleanField()),
                ('time13', models.BooleanField()),
                ('time14', models.BooleanField()),
                ('time15', models.BooleanField()),
                ('time16', models.BooleanField()),
                ('time17', models.BooleanField()),
                ('time18', models.BooleanField()),
            ],
        ),
    ]
