# Generated by Django 5.1.4 on 2024-12-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timeslot',
            name='doctor',
        ),
        migrations.DeleteModel(
            name='WorkingHours',
        ),
        migrations.DeleteModel(
            name='Doctors',
        ),
        migrations.DeleteModel(
            name='Timeslot',
        ),
    ]
